CREATE DATABASE JDPodrozeDB CONTAINMENT = NONE ON PRIMARY (
    NAME = 'JDPodrozeDB_data', FILENAME = 'D:\Databases\JDPodroze\JDPodrozeDB_data.mdf', SIZE = 22784KB , MAXSIZE = 256000KB , FILEGROWTH = 1024KB
) LOG ON (
    NAME = 'JDPodrozeDB_logs', FILENAME = 'D:\Databases\JDPodroze\JDPodrozeDB_log.ldf', SIZE = 26816KB , MAXSIZE = 512000KB , FILEGROWTH = 10%
);
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
BEGIN
EXEC [JDPodrozeDB].[dbo].[sp_fulltext_database] @action = 'enable'
END
GO

ALTER DATABASE [JDPodrozeDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [JDPodrozeDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [JDPodrozeDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [JDPodrozeDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [JDPodrozeDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [JDPodrozeDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [JDPodrozeDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [JDPodrozeDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [JDPodrozeDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [JDPodrozeDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [JDPodrozeDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [JDPodrozeDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [JDPodrozeDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [JDPodrozeDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [JDPodrozeDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [JDPodrozeDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [JDPodrozeDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [JDPodrozeDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [JDPodrozeDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [JDPodrozeDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [JDPodrozeDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [JDPodrozeDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [JDPodrozeDB] SET RECOVERY FULL 
GO

ALTER DATABASE [JDPodrozeDB] SET MULTI_USER 
GO

ALTER DATABASE [JDPodrozeDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [JDPodrozeDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [JDPodrozeDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [JDPodrozeDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [JDPodrozeDB] SET READ_WRITE 
GO

CREATE TABLE [JDPodrozeDB].[dbo].[Contact] (
    Id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Contact PRIMARY KEY CLUSTERED,
    NameAndSurname NVARCHAR(100) NOT NULL,
    Email NVARCHAR(150) NOT NULL,
    Content NVARCHAR(1024) NOT NULL
);

CREATE TABLE [JDPodrozeDB].[dbo].[Users] (
    Id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Users PRIMARY KEY CLUSTERED,
    Login VARCHAR(50) NOT NULL,
    Password VARCHAR(255) NOT NULL,
    FirstName NVARCHAR(50) NOT NULL,
    LastName NVARCHAR(50) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    IsAdmin BIT NOT NULL CONSTRAINT DF_Users_IsAdmin DEFAULT 0
);

CREATE TABLE [JDPodrozeDB].[dbo].[Visits] (
    Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_Visits_Id DEFAULT NEWID(),
    TypeId INT NULL,
    Description NVARCHAR(256) NULL,
    IP NVARCHAR(40) NULL,
    DateAndTime DATETIME2(7) NULL,
    CONSTRAINT PK_Visits PRIMARY KEY CLUSTERED (Id)
);

CREATE TABLE [JDPodrozeDB].[dbo].[NewsletterEmails] (
    Id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_NewsletterEmails PRIMARY KEY CLUSTERED,
    Email NVARCHAR(150) NOT NULL,
    Name NVARCHAR(50) NOT NULL
);

CREATE TABLE [JDPodrozeDB].[dbo].[Excursions] (
    Id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Excursions PRIMARY KEY CLUSTERED,
    Title NVARCHAR(255) NOT NULL,
    ShortDescription NVARCHAR(255) NOT NULL,
    Description NVARCHAR(MAX) NOT NULL,
    Active BIT NOT NULL,
    InCarousel BIT NOT NULL,
    DateFrom DATE NULL,
    DateTo DATE NULL,
    PriceGross DECIMAL(8,2) NOT NULL,
    PriceNet DECIMAL(8, 2) NOT NULL,
    Discount BIT NOT NULL CONSTRAINT DF_Excursions_Discount DEFAULT 0,
    DiscountPriceGross DECIMAL(8,2) NOT NULL CONSTRAINT DF_Excursions_DiscountPriceGross DEFAULT 0.00,
    Seats INT NOT NULL CONSTRAINT DF_Excursions_Seats DEFAULT 0,
    IsTemplate BIT NOT NULL CONSTRAINT DF_Excursions_IsTemplate DEFAULT 0,
    IsDeleted BIT NOT NULL CONSTRAINT DF_Excursions_IsDeleted DEFAULT 0
);

CREATE TABLE [JDPodrozeDB].[dbo].[ExcursionsPickupPoints] (
    Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_ExcursionsPickupPoints_Id DEFAULT NEWID(),
    ExcursionId INT NOT NULL,
    Name NVARCHAR(50) NOT NULL,
    CONSTRAINT PK_ExcursionsPickupPoints PRIMARY KEY CLUSTERED (Id),
    CONSTRAINT FK_ExcursionsPickupPoints_Excursions FOREIGN KEY (ExcursionId)
        REFERENCES [JDPodrozeDB].[dbo].[Excursions] (Id)
);

CREATE TABLE [JDPodrozeDB].[dbo].[ExcursionsImages] (
    Id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_ExcursionsImages PRIMARY KEY CLUSTERED,
    ExcursionId INT NOT NULL,
    Name NVARCHAR(100) NOT NULL,
    Type VARCHAR(4) NOT NULL,
    [Order] INT NOT NULL,
    CONSTRAINT FK_ExcursionsImages_Excursions FOREIGN KEY (ExcursionId)
        REFERENCES [JDPodrozeDB].[dbo].[Excursions] (Id)
);

CREATE TABLE [JDPodrozeDB].[dbo].[ExcursionsOrders] (
    OrderId UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_ExcursionsOrders_OrderId DEFAULT NEWID(),
    ExcursionId INT NOT NULL,
    PaymentMethod CHAR(1) NOT NULL CONSTRAINT DF_ExcursionsOrders_PaymentMethod DEFAULT 'T',
    PaymentStatus CHAR(1) NOT NULL CONSTRAINT DF_ExcursionsOrders_PaymentStatus DEFAULT 'N',
    BookerId INT NULL,
    Price DECIMAL(8, 2) NOT NULL CONSTRAINT DF_ExcursionsOrders_Price DEFAULT 0.00,
    PickupPointId UNIQUEIDENTIFIER NULL,
    CONSTRAINT PK_ExcursionsOrders PRIMARY KEY CLUSTERED (OrderId),
    CONSTRAINT FK_ExcursionsOrders_Excursions FOREIGN KEY (ExcursionId)
        REFERENCES [JDPodrozeDB].[dbo].[Excursions] (Id),
    CONSTRAINT CH_ExcursionsOrders_PaymentMethod CHECK (PaymentMethod = 'P' OR PaymentMethod = 'T'),
    CONSTRAINT CH_ExcursionsOrders_PaymentStatus CHECK (PaymentStatus = 'N' OR PaymentStatus = 'P')
);

CREATE TABLE [JDPodrozeDB].[dbo].[ExcursionsParticipants] (
    Id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_ExcursionsParticipants PRIMARY KEY CLUSTERED,
    BookerId INT NULL,
    OrderId UNIQUEIDENTIFIER NOT NULL,
    Name NVARCHAR(50) NOT NULL,
    Surname NVARCHAR(50) NOT NULL,
    Email NVARCHAR(150) NULL,
    TelephoneNumber NVARCHAR(12) NULL,
    BirthDate DATE NOT NULL,
    UserId INT NULL,
    Discount BIT NOT NULL CONSTRAINT DF_ExcursionsParticipants_Discount DEFAULT 0,
    CONSTRAINT FK_ExcursionsParticipants_ExcursionsOrders FOREIGN KEY (OrderId)
        REFERENCES [JDPodrozeDB].[dbo].[ExcursionsOrders] (OrderId),
    CONSTRAINT FK_ExcursionsParticipants_Users FOREIGN KEY (UserId)
        REFERENCES [JDPodrozeDB].[dbo].[Users] (Id)
);