CREATE TABLE [JDPodrozeDB].[dbo].[Contact] (
    Id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Contact PRIMARY KEY CLUSTERED,
    NameAndSurname NVARCHAR(100) NOT NULL,
    Email NVARCHAR(150) NOT NULL,
    Content NVARCHAR(1024) NOT NULL
);